steps:
  build:
    image: rust
    commands:
      - cargo build --locked
  test:
    image: rust
    commands:
      - cargo test --locked
  lint:
    image: rust
    commands:
      - rustup component add rustfmt clippy
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps
