[package]
name = "cargo-deps"
description = "Cargo subcommand to get a list of dependencies in a typical build"
categories = ["development-tools", "development-tools::cargo-plugins"]
keywords = ["cargo", "dependencies"]
version = "0.1.0"
edition = "2021"
rust-version = "1.58"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
readme = "README.md"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0"
itertools = "0.10"
lazy-regex = "2.2"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
